VERSION: 1.15-alpha

AUTHORS:
    - 'Romitou#9685'
    - 'Xamez#8497'
    - 'TitiLaPierre#3934'

PREFIX:
    GENERAL: '&3&lWolfo &7&l▪ &r'
    TITLE: '&7&l▪ &3&lWolfo &7&l▪'

CONFIG:
    SELF_VOTE: 'off'

# Unused (at this time)
ANIMATION:
    SELECTION: ARROW

LANGUAGES:
    DEFAULT: fr_fr
    PROPERTIES:
        fr_fr:
            NAME: '&9Français'
            ITEM: player head
            NBT: '{SkullOwner:{Id:"395a599f-9588-4fe2-ada9-07cd81262996",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTEyNjlhMDY3ZWUzN2U2MzYzNWNhMWU3MjNiNjc2ZjEzOWRjMmRiZGRmZjk2YmJmZWY5OWQ4YjM1Yzk5NmJjIn19fQ=="}]}}}'
        en_us:
            NAME: '&cEnglish'
            ITEM: player head
            NBT: '{SkullOwner:{Id:"ec3a65b7-41d5-40cf-8a0b-0256d065a57d",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjI0MWE2OTdmNmRmYjFjNTdjZGEzMjdiYWE2NzMyYTc4MjhjMzk4YmU0ZWJmZGJkMTY2YzIzMmJjYWUyYiJ9fX0="}]}}}'

COSMETICS:
    PARTICLE:
        - explosion;bone meal
        - firework;firework
        - crit;trident
        - critmagic;trident of sharpness 1
        - smoke;campfire
        - angryvillager;baked potato
        - happyvillager;potato
        - waterdrip;water bucket
        - flame;flint and steel
        - lavadrip;lava bucket
        - note;note block
        - portal;ender eye
        - enchantmenttable;enchanting table
        - cloud;nether star
        - snowball;snowball
        - slime;slimeball
        - heart;apple
    EFFECT:
        - wings;elytra
        - nyancat;white wool
        - rings;string
        - spiral;lead

TIME:
    START: '10'
    VOTE: '30'
    DEBATE: '60'
    END: '20'

ROLES:
    WEREWOLF:
        ITEM: player head
        NBT: '{SkullOwner:{Id:"9cd0e1fb-c1d6-4859-9392-13655a000118",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY4ZDQzMTI5MzliYjMxMTFmYWUyOGQ2NWQ5YTMxZTc3N2Y4ZjJjOWZjNDI3NTAxY2RhOGZmZTNiMzY3NjU4In19fQ=="}]}}}'
        AURA: WEREWOLF
    WEREWOLF_ALPHA:
        ITEM: player head
        NBT: '{SkullOwner:{Id:"736e9be2-4984-4cbc-bbb6-9ab419bb55bc",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjgzYTJhYTlkMzczNGI5MTlhYzI0Yzk2NTllNWUwZjg2ZWNhZmJmNjRkNDc4OGNmYTQzM2JiZWMxODllOCJ9fX0="}]}}}'
        AURA: WEREWOLF
    TOWNSFOLK_CURSED:
        ITEM: bread
        AURA: WW_TF
    TOWNSFOLK:
        ITEM: bread
        AURA: TOWNSFOLK
    CUPID:
        ITEM: player head
        NBT: '{SkullOwner:{Id:"94c9b15f-f65a-427d-a699-ad0d4d5489f6",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjRlYWY4OTQyOGEzNjQ5YzI2ZWRjMWY3MWNjMTlmMjYzZTlmNGViMzFlZDE4Yzk3Njg2YWFjODJmNzY0MjQyIn19fQ=="}]}}}'
        AURA: TOWNSFOLK
    SEER:
        ITEM: eyes of ender
        AURA: TOWNSFOLK
    SEER_AURA:
        ITEM: ender pearl
        AURA: TOWNSFOLK
    CRAZY:
        ITEM: player head
        NBT: '{SkullOwner:{Id:"7e18508f-feb6-445b-8020-2c7cb79ace7c",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFiZWNhY2VjODU4YTE5ODQ4ODYwYjI1MjJjMzI5MzZhZGYxNTg4YzFlZjQyMzc5NDAzZmVmODNkYTRiYiJ9fX0="}]}}}'
        AURA: SOLO
    SHOOTER:
        ITEM: bow
        AURA: TOWNSFOLK
    HEADHUNTER:
        ITEM: player head
        NBT: '{SkullOwner:{Id:"9d58f311-003b-4d1d-8ba8-b678e182bab3",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2MxZGYwZGI4ZDQ3NzNjYzI1NWE2M2I4ZjBiMGU0Y2RkN2Q3NGMzYjRjNjc1MzYyMTY4NDYwYmM2N2JiMzAyZSJ9fX0="}]}}}'
        AURA: SOLO
    DOCTOR:
        ITEM: apple
        AURA: TOWNSFOLK
    WITCH:
        ITEM: player head
        NBT: '{SkullOwner:{Id:"7f92b3d6-5ee0-4ab6-afae-2206b9514a63",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBlMTNkMTg0NzRmYzk0ZWQ1NWFlYjcwNjk1NjZlNDY4N2Q3NzNkYWMxNmY0YzNmODcyMmZjOTViZjlmMmRmYSJ9fX0="}]}}}'
        AURA: TOWNSFOLK

MANAGE:
    FORCESTART: light green dye
    SEPARATOR: light blue stained glass pane
    CLOSED: red dye
    WHITELIST: orange dye
    OPEN: green dye

SETUP:
    MIDDLE: beacon
    SPAWNPOINT: ender pearl
    SEPARATOR: light blue stained glass pane
    BEGIN: light green dye
    END: red dye

OTHER_ITEMS:
    CLOSE: barrier
    LANG: oak sign

GAME:
    PRIVACY: OPEN
    LOCATIONS:
    SETUP:
        STEPS:
        FINISH: false
